services:
  home-index:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index
    depends_on:
      - meilisearch
    environment:
      - DEBUG=True
      - MEILISEARCH_HOST=http://meilisearch:7700
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - ./docker-data/home-index:/home-index
      - ./docker-data/files:/files
  meilisearch:
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    image: getmeili/meilisearch:v1.15.2
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - ./docker-data/meilisearch:/meili_data
