services:
  home-index:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index
    depends_on:
      - meilisearch
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - TZ=America/Los_Angeles
      - WAIT_FOR_DEBUG_CLIENT
    ports:
      - '5678:5678' # debugpy
    restart: unless-stopped
    volumes:
      - ./bind-mounts/home-index:/home-index
      - ./bind-mounts/home-index-root:/home-index-root
  meilisearch:
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/meilisearch:/meili_data
  home-index-test_module_1:
    build:
      context: ./test/test_module_1/
      dockerfile: Dockerfile
    container_name: home-index-test_module_1
    environment:
      - TZ=America/Los_Angeles
      #- WAIT_FOR_DEBUG_CLIENT
    ports:
      - '5678:5679' # debugpy
    restart: unless-stopped
    volumes:
      - ./bind-mounts/test-files:/files
