---
services:
  meilisearch:
    container_name: home-index-devcontainer-meilisearch
    environment:
      - MEILI_LOG_LEVEL=debug
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    expose:
      - '7700'
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/meili_data:/meili_data
  tika:
    command: ["--config", "/config/tika-config.xml"]
    container_name: home-index-devcontainer-tika
    environment:
      - TZ=America/Los_Angeles
    expose:
      - '9998'
    image: apache/tika:latest-full
    restart: unless-stopped
    volumes:
      - ./bind-mounts/tika:/config
      - /home/ns/shared:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index-devcontainer-app
    depends_on:
      - meilisearch
      - tika
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DOMAIN=private.0819870.xyz
      - MEILISEARCH_HOST=http://meilisearch:7700
      - NVIDIA_VISIBLE_DEVICES=all
      - TIKA_SERVER_ENDPOINT=http://tika:9998
      - TZ=America/Los_Angeles
    ipc: host
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - ./bind-mounts/home-index:/app/data
      - /home/ns/shared:/data
      - ./bind-mounts/home-index/pytorch:/root/.cache/torch/