version: '3.9'
services:
  home-index:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index
    depends_on:
      - meilisearch
      - home-index-example-module
    environment:
      - DEBUG=True
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MODULES=http://home-index-example-module:9000
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - ./bind-mounts/home-index:/home-index
      - ./bind-mounts/files:/files
  meilisearch:
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - ./bind-mounts/meilisearch:/meili_data
  home-index-example-module:
    build:
      context: ./examples/module_template/
      dockerfile: Dockerfile
    container_name: home-index-example-module
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - ./bind-mounts/files:/files
