x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]
  ulimits:
    memlock:
      soft: -1
      hard: -1
    stack:
      soft: 67108864
      hard: 67108864

services:
  devcontainer:
    build:
      args:
        CUDA_MAJOR: "${CUDA_MAJOR:-12}"
        CUDA_MINOR: "${CUDA_MINOR:-9}"
    <<: *gpu
