services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    command: ["/bin/sh"]
    container_name: home-index-devcontainer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - ../:/workspace
      - ../docker-data:/var/lib/docker
      - /home/ns/.ssh:/home/ns/.ssh:ro
      - /home/ns/shared:/mnt/shared:ro