services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    command: [ "/bin/sh" ]
    container_name: home-index-devcontainer
    hostname: home-index-devcontainer
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
      - ../docker-data:/var/lib/docker
      - ~/.ssh:/tmp/.ssh:ro
