---
services:
  home-index-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash"]
    container_name: home-index-devcontainer
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock