name: Docker Compose Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Build containers
        run: docker compose build
      - name: Start services
        run: docker compose up -d
      - name: Wait for Meilisearch
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:7700/health > /dev/null; then
              break
            fi
            sleep 2
          done
      - name: Run tests
        env:
          EXTERNAL_MEILISEARCH: '1'
          MEILISEARCH_HOST: 'http://localhost:7700'
        run: pytest -q
      - name: Stop services
        run: docker compose down
