name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Build containers
        run: docker compose build
      - name: Start services
        run: docker compose up -d
      - name: File Documents Match The Expected Schema
        run: pytest -q tests/test_meilisearch_schema.py::test_file_documents_match_the_expected_schema
      - name: Chunk Documents Follow The Chunk Schema
        run: pytest -q tests/test_meilisearch_file_chunk_schema.py::test_chunk_documents_follow_the_chunk_schema
      - name: Modules Communicate Via XML-RPC
        env:
          EXTERNAL_MEILISEARCH: '1'
          MEILISEARCH_HOST: 'http://localhost:7700'
        run: pytest -q tests/test_run_server_module.py::test_modules_communicate_via_xml_rpc
      - name: Modules Can Add And Remove Chunk Data
        env:
          EXTERNAL_MEILISEARCH: '1'
          MEILISEARCH_HOST: 'http://localhost:7700'
        run: pytest -q tests/test_chunk_integration.py::test_modules_can_add_and_remove_chunk_data
      - name: Modules May Return Only Updated Documents
        env:
          EXTERNAL_MEILISEARCH: '1'
          MEILISEARCH_HOST: 'http://localhost:7700'
        run: pytest -q tests/test_chunk_integration.py::test_modules_may_return_only_updated_documents
      - name: Retry Helper Stops When A Call Succeeds
        run: pytest -q tests/test_retry.py::test_retry_helper_stops_when_a_call_succeeds
      - name: Retry Helper Fails After Repeated Errors
        run: pytest -q tests/test_retry.py::test_retry_helper_fails_after_repeated_errors
      - name: Indexing Runs Across Many Files And Modules
        env:
          EXTERNAL_MEILISEARCH: '1'
          MEILISEARCH_HOST: 'http://localhost:7700'
        run: pytest -q tests/test_large_indexing.py::test_indexing_runs_across_many_files_and_modules
      - name: Cron Schedules Are Parsed From The Environment
        run: pytest -q tests/test_schedule.py::test_cron_schedules_are_parsed_from_the_environment
      - name: Malformed Cron Expressions Raise ValueError
        run: pytest -q tests/test_schedule.py::test_malformed_cron_expressions_raise_valueerror
      - name: Text Embeddings Use SentenceTransformer Models
        run: pytest -q tests/test_embeddings.py::test_text_embeddings_use_sentence_transformer_models
      - name: Scheduler Attaches A CronTrigger Job For Periodic Indexing
        run: pytest -q tests/test_schedule.py::test_scheduler_attaches_a_crontrigger_job_for_periodic_indexing
      - name: Module Migrations Persist Version Upgrades
        run: pytest -q tests/test_module_migrations.py::test_module_migrations_persist_version_upgrades
      - name: Metadata Persists If The Archive Directory Is Temporarily Missing
        run: pytest -q tests/test_archive_support.py::test_metadata_persists_if_the_archive_directory_is_temporarily_missing
      - name: Metadata And Symlinks Are Purged After An Archive File Is Removed
        run: pytest -q tests/test_archive_support.py::test_metadata_and_symlinks_are_purged_after_an_archive_file_is_removed
      - name: TokenTextSplitter Divides Chunk Text Into Smaller Documents
        run: pytest -q tests/test_chunk_utils.py::test_tokentextsplitter_divides_chunk_text_into_smaller_documents
      - name: Segments With Headers Convert To Chunk Documents Referencing The Source File
        run: pytest -q tests/test_chunk_utils.py::test_segments_with_headers_convert_to_chunk_documents_referencing_the_source_file
      - name: Stop services
        run: docker compose down
