name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - run: docker-compose -f .devcontainer/docker-compose.yml up --build -d
      - run: docker exec ${REPO}-devcontainer postStart.sh
      - run: docker exec ${REPO}-devcontainer ./check.sh

      - run: docker exec ${REPO}-devcontainer docker build -f Dockerfile -t ${REPO}:ci --build-arg COMMIT_SHA=$(git rev-parse HEAD) .
      - run: docker exec ${REPO}-devcontainer docker build -f Dockerfile.module -t ${REPO}-module:ci --build-arg COMMIT_SHA=$(git rev-parse HEAD) .

      - run: |
          set -euo pipefail
          FEATURES=$(ls features | grep '^F')
          SHA=$(git rev-parse HEAD)
          for f in $FEATURES; do
            docker exec \
              -e IMAGE=${REPO}:ci \
              -e COMMIT_SHA=${SHA} \
              -e MODULE_BASE_IMAGE=${REPO}-module:ci \
              ${REPO}-devcontainer \
              bash -lc "source venv/bin/activate && pytest -q features/${f}/test/acceptance.py"
          done

      - run: docker-compose -f .devcontainer/docker-compose.yml down -v
