name: Test

on:
  push:
    branches: ['**']

jobs:
  test-all-features:
    runs-on: ubuntu-latest
    env:
      FEATURES: "F1"
    steps:
      - uses: actions/checkout@v4.2.2

      # ── dev container up once ─────────────────────────────────────────
      - name: Start dev container
        run: docker-compose -f .devcontainer/docker-compose.yml up --build -d

      - name: Wait until venv is ready
        run: |
          for i in {1..30}; do
            if docker exec home-index-devcontainer test -d /workspace/venv; then exit 0; fi
            sleep 2
          done
          echo "Dev container never became ready" >&2
          exit 1

      # ── quality gates (once) ─────────────────────────────────────────
      - name: Format & lint
        run: docker exec home-index-devcontainer ./check.sh

      # ── build release image once ─────────────────────────────────────
      - name: Build release image
        run: docker exec home-index-devcontainer \
               docker build -f Dockerfile -t home-index:test .

      - name: Run tests for every feature
        run: |
          set -Eeuo pipefail
          for feature in $FEATURES; do
            echo "::group::Testing $feature"
            docker exec home-index-devcontainer bash -Eeuo pipefail -c '
              FEATURE="$0"

              # Path inside the dev container workspace
              UNIT_PATH="/workspace/features/${FEATURE}/test/unit.py"
              ACC_PATH="/workspace/features/${FEATURE}/test/acceptance.py"

              # Run unit tests only if the file exists
              if [ -f "$UNIT_PATH" ]; then
                echo "› unit.py found – running unit tests"
                docker run --rm home-index:test pytest -q "features/${FEATURE}/test/unit.py"
              else
                echo "::notice title=No unit tests::${FEATURE} has no unit.py – skipping unit tests"
              fi

              # acceptance.py is mandatory
              echo "› running acceptance tests"
              docker run --rm home-index:test pytest -q "features/${FEATURE}/test/acceptance.py"
            ' "$feature"
            echo "::endgroup::"
          done

      # ── tear down once everything is done ────────────────────────────
      - name: Stop dev container
        if: always()
        run: docker-compose -f .devcontainer/docker-compose.yml down -v
