name: Test

on:
  push:
    branches: ['**']

jobs:
  test-all-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - feature: F1
            name: my home server to be available when I need it
    steps:
      - uses: actions/checkout@v4.2.2

      # ── dev container up once ─────────────────────────────────────────
      - name: Start dev container
        run: docker-compose -f .devcontainer/docker-compose.yml up --build -d

      - name: Wait until venv is ready
        run: |
          for i in {1..30}; do
            if docker exec home-index-devcontainer test -d /workspace/venv; then exit 0; fi
            sleep 2
          done
          echo "Dev container never became ready" >&2
          exit 1

      # ── quality gates (once) ─────────────────────────────────────────
      - name: Format & lint
        run: docker exec home-index-devcontainer ./check.sh

      # ── build release image once ─────────────────────────────────────
      - name: Build release image
        run: docker exec home-index-devcontainer \
               docker build -f Dockerfile -t repo-runtime:latest .

      - name: Test ${{ matrix.feature }}: ${{ matrix.name }}
        run: docker exec home-index-devcontainer \
          docker-compose -f features/${{ matrix.feature }}/test/docker-compose.yml up --abort-on-container-exit

      # ── tear down once everything is done ────────────────────────────
      - name: Stop dev container
        if: always()
        run: docker-compose -f .devcontainer/docker-compose.yml down -v
