name: test-features

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
      FEATURES: $(ls features | grep '^F')
    steps:
      - uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Dev container
      - run: docker-compose -f .devcontainer/docker-compose.yml up --build -d
      - run: docker exec ${REPO}-devcontainer ./postStart.sh
      - run: docker exec ${REPO}-devcontainer ./check.sh

      # Build release image for acceptance tests
      - run: docker exec ${REPO}-devcontainer docker build -f Dockerfile -t ${REPO}:ci .

      # Acceptance tests
      - run: |
          set -euo pipefail
          for f in $FEATURES; do
            docker exec -e IMAGE=${REPO}:ci ${REPO}-devcontainer \
              pytest -q "features/${f}/test"
          done

      - run: docker-compose -f .devcontainer/docker-compose.yml down -v
