name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: quiet
      COMPOSE_PROGRESS: quiet

    steps:
      - uses: actions/checkout@v4

      - name: Start dev-container
        run: |
          docker compose -f .devcontainer/docker-compose.yml up --build -d --quiet-pull > /dev/null

      - name: postStart
        run: docker exec ${REPO}-devcontainer postStart.sh > /dev/null

      - name: Build primary image
        run: |
          docker exec ${REPO}-devcontainer \
            docker build -q -f Dockerfile \
            -t ${REPO}:ci --build-arg COMMIT_SHA=$(git rev-parse HEAD) .

      - name: Build module image
        run: |
          docker exec ${REPO}-devcontainer \
            docker build -q \
            -f features/F4/home_index_module/Dockerfile \
            -t ${REPO}-module:ci \
            --build-arg COMMIT_SHA=$(git rev-parse HEAD) .

      - name: Run checks
        run: |
          docker exec -e IMAGE=${REPO}:ci \
            -e MODULE_BASE_IMAGE=${REPO}-module:ci \
            -e COMMIT_SHA=$(git rev-parse HEAD) -e CI=true \
            ${REPO}-devcontainer ./check.sh

      - name: Stop dev-container
        run: docker compose -f .devcontainer/docker-compose.yml down -v > /dev/null
